function readonlyArrayOf<T extends string>(object: Record<T, true>): readonly T[] {
  return Object.keys(object) as T[];
}

type TupleToUnion<T extends readonly _[]> = T[number];

type Missing<U extends string, T extends readonly string[]> = Exclude<U, TupleToUnion<T>> extends never ? never : Exclude<U, TupleToUnion<T>>;
type Extras<U extends string, T extends readonly string[]> = Exclude<TupleToUnion<T>, U> extends never ? never : Exclude<TupleToUnion<T>, U>;
type UniqueTuple<T extends readonly _[], R extends readonly _[] = []> =
  T extends readonly [infer H, ...infer Rest]
    ? H extends R[number] ? never : UniqueTuple<Rest, readonly [...R, H]>
    : T;
type ExactTuple<T extends readonly string[], U extends string> =
    UniqueTuple<T> extends never ? never :
    Missing<U, T> extends never ?
    Extras<U, T> extends never ? T : ['EXTRA_TAGS', Extras<U, T>] :
    ['MISSING_TAGS', Missing<U, T>];

export const VoidHTMLTags = [
  "area",
  "base",
  "br",
  "col",
  "embed",
  "hr",
  "img",
  "input",
  "link",
  "meta",
  "param",
  "source",
  "track",
  "wbr"
] as const;

export const HTMLTags = [
  "object",
  "a",
  "abbr",
  "address",
  "area",
  "article",
  "aside",
  "audio",
  "b",
  "base",
  "bdi",
  "bdo",
  "blockquote",
  "body",
  "br",
  "button",
  "canvas",
  "caption",
  "cite",
  "code",
  "col",
  "colgroup",
  "data",
  "datalist",
  "dd",
  "del",
  "details",
  "dfn",
  "dialog",
  "div",
  "dl",
  "dt",
  "em",
  "embed",
  "fieldset",
  "figcaption",
  "figure",
  "footer",
  "form",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "head",
  "header",
  "hgroup",
  "hr",
  "html",
  "i",
  "iframe",
  "img",
  "input",
  "ins",
  "kbd",
  "label",
  "legend",
  "li",
  "link",
  "main",
  "map",
  "mark",
  "menu",
  "meta",
  "meter",
  "nav",
  "noscript",
  "ol",
  "optgroup",
  "option",
  "output",
  "p",
  "picture",
  "pre",
  "progress",
  "q",
  "rp",
  "rt",
  "ruby",
  "s",
  "samp",
  "script",
  "search",
  "section",
  "select",
  "slot",
  "small",
  "source",
  "span",
  "strong",
  "style",
  "sub",
  "summary",
  "sup",
  "table",
  "tbody",
  "td",
  "template",
  "textarea",
  "tfoot",
  "th",
  "thead",
  "time",
  "title",
  "tr",
  "track",
  "u",
  "ul",
  "var",
  "video",
  "wbr"
] as const;
export const SVGTags = [
  "symbol",
  "a",
  "script",
  "style",
  "title",
  "animate",
  "animateMotion",
  "animateTransform",
  "circle",
  "clipPath",
  "defs",
  "desc",
  "ellipse",
  "feBlend",
  "feColorMatrix",
  "feComponentTransfer",
  "feComposite",
  "feConvolveMatrix",
  "feDiffuseLighting",
  "feDisplacementMap",
  "feDistantLight",
  "feDropShadow",
  "feFlood",
  "feFuncA",
  "feFuncB",
  "feFuncG",
  "feFuncR",
  "feGaussianBlur",
  "feImage",
  "feMerge",
  "feMergeNode",
  "feMorphology",
  "feOffset",
  "fePointLight",
  "feSpecularLighting",
  "feSpotLight",
  "feTile",
  "feTurbulence",
  "filter",
  "foreignObject",
  "g",
  "image",
  "line",
  "linearGradient",
  "marker",
  "mask",
  "metadata",
  "mpath",
  "path",
  "pattern",
  "polygon",
  "polyline",
  "radialGradient",
  "rect",
  "set",
  "stop",
  "svg",
  "switch",
  "text",
  "textPath",
  "tspan",
  "use",
  "view"
] as const;
export const MathMLTags = [
  "a",
  "annotation",
  "annotation-xml",
  "maction",
  "math",
  "merror",
  "mfrac",
  "mi",
  "mmultiscripts",
  "mn",
  "mo",
  "mover",
  "mpadded",
  "mphantom",
  "mprescripts",
  "mroot",
  "mrow",
  "ms",
  "mspace",
  "msqrt",
  "mstyle",
  "msub",
  "msubsup",
  "msup",
  "mtable",
  "mtd",
  "mtext",
  "mtr",
  "munder",
  "munderover",
  "semantics"
] as const;

type _CheckVoidHTMLTags = ExactTuple<typeof VoidHTMLTags, VoidHTMLTag>;
type _CheckHTMLTags = ExactTuple<typeof HTMLTags, HTMLTag>;
type _CheckSVGTags = ExactTuple<typeof SVGTags, SVGTag>;
type _CheckMathMLTags = ExactTuple<typeof MathMLTags, MathMLTag>;

export function isHTMLTag(tag: string): tag is HTMLTag {
  return HTMLTags.includes(tag as HTMLTag);
}

export function isVoidHTMLTag(tag: string): tag is VoidHTMLTag {
  return VoidHTMLTags.includes(tag as VoidHTMLTag);
}